server:
  port: 3030

spring:
  application:
    name: payment-client
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    
